import z from 'zod/v4'
import { ActionButtonItemSchemaV6, ExportV6Schema } from '../v6'
import {
  AudioItemSchemaV4,
  BookItemSchemaV4,
  ImageItemSchemaV4,
  TextItemSchemaV4,
  VideoItemSchemaV4,
  WebpageItemSchemaV4,
} from '../v4'
import { SizeSchema } from '../../schemas/common'
import { PDFItemSchemaV5 } from '../v5'
import { omit } from 'lodash-es'

const mediaItemOmitMask = {
  thumbnail: true,
  customThumbnail: true,
  internallyHosted: true,
} as const

const V7Props = {
  thumbnail: z
    .object({
      renditions: z
        .object({
          source: z.string(),
          format: z.string(),
          size: SizeSchema,
          isPrimary: z.boolean(),
          isAutoGenerated: z.boolean(),
        })
        .array(),
    })
    .optional(),
  layer: z.int().default(0),
}

const actionProps = {
  actionType: z.enum(['internalLink', 'externalLink']).nullish(),
  action: z.string().nullish(),
}

export const TextItemSchemaV7 = z.object({
  ...TextItemSchemaV4.omit({ customThumbnail: true }).shape,
  ...V7Props,
})
export const ActionButtonItemSchemaV7 = z.object({
  ...ActionButtonItemSchemaV6.omit({ thumbnail: true, actionType: true }).shape,
  ...V7Props,
  actionType: actionProps.actionType,
})
export const AudioItemSchemaV7 = z.object({
  ...AudioItemSchemaV4.omit(omit(mediaItemOmitMask, 'thumbnail')).shape,
  ...V7Props,
})
export const BookItemSchemaV7 = z.object({
  ...BookItemSchemaV4.omit(omit(mediaItemOmitMask, 'thumbnail')).shape,
  ...V7Props,
})
export const ImageItemSchemaV7 = z.object({
  ...ImageItemSchemaV4.omit(omit(mediaItemOmitMask, 'thumbnail')).shape,
  ...V7Props,
  ...actionProps,
})
export const PDFItemSchemaV7 = z.object({
  ...PDFItemSchemaV5.omit(mediaItemOmitMask).shape,
  ...V7Props,
})
export const VideoItemSchemaV7 = z.object({
  ...VideoItemSchemaV4.omit(mediaItemOmitMask).shape,
  ...V7Props,
})
export const WebpageItemSchemaV7 = z.object({
  ...WebpageItemSchemaV4.omit(mediaItemOmitMask).shape,
  ...V7Props,
})

export const ItemSchemaV7 = z.discriminatedUnion('type', [
  ActionButtonItemSchemaV7,
  TextItemSchemaV7,
  AudioItemSchemaV7,
  BookItemSchemaV7,
  ImageItemSchemaV7,
  PDFItemSchemaV7,
  VideoItemSchemaV7,
  WebpageItemSchemaV7,
])

export const ExportV7Schema = z.object({
  ...ExportV6Schema.shape,
  version: z.literal(7),
  items: z.array(ItemSchemaV7).nullish(),
})

export type ExportV7 = z.infer<typeof ExportV7Schema>
