import { JobTypeMap } from './index.js'
import { config } from '../config.js'
import { s3Service, tapestryKey } from '../services/s3-service.js'
import { prisma } from '../db.js'
import { takeTapestryScreenshots } from './thumbnail-generators/tapestry.js'
import { Item } from '@prisma/client'
import { generatePrimaryThumbnail, hasInherentThumbnail } from './thumbnail-generators/index.js'
import { processItemThumbnail } from './process-item-thumbnail.js'

// the ratio of the thumbnail as displayed in the UI
const DESKTOP_WIDTH = 2000
const DESKTOP_HEIGHT = Math.floor(DESKTOP_WIDTH * (10 / 21))

export async function generateTapestryThumbnails({
  tapestryId,
  generationStrategy = 'standard',
}: JobTypeMap['generate-tapestry-thumbnails']) {
  const tapestry = await prisma.tapestry.findUniqueOrThrow({
    where: { id: tapestryId },
    include: {
      items:
        generationStrategy === 'standard'
          ? {
              where: { scheduledThumbnailProcessing: { not: null } },
            }
          : true,
    },
  })

  await prisma.item.updateMany({
    where: { tapestryId },
    data: { scheduledThumbnailProcessing: null },
  })

  const itemsToScreenshot: Item[] = []
  for (const item of tapestry.items) {
    if (hasInherentThumbnail(item)) {
      try {
        await processItemThumbnail(
          item.id,
          () => generatePrimaryThumbnail(item),
          (item.scheduledThumbnailProcessing || generationStrategy) === 'recreate',
        )
      } catch (error) {
        console.error(`Error while generating thumbnail for ${item.type} item ${item.id}:`, error)
      }
    } else {
      itemsToScreenshot.push(item)
    }
  }

  let thumbnails: ReturnType<typeof takeTapestryScreenshots> | undefined
  try {
    thumbnails = takeTapestryScreenshots(`/t/${tapestryId}`, tapestry.ownerId, {
      windowSize: { width: DESKTOP_WIDTH, height: DESKTOP_HEIGHT },
      timeout: config.worker.tapestryThumbnailGenerationTimeout,
    })

    // The first thumbnail generated by the generator is a screenshot of the whole tapestry
    const { done, value } = await thumbnails.next()
    if (done) throw new Error('Expected at least one value from generator but got none')

    const thumbnailKey = tapestryKey(tapestryId, `thumbnail.${value.extension}`)
    await s3Service.putObject(thumbnailKey, value.data, `image/${value.format}`)
    await prisma.tapestry.update({
      where: { id: tapestryId },
      data: { thumbnail: thumbnailKey },
    })

    // Use the generator to perform screenshots of the tapestry items as well, while the browser page is open
    for (const item of itemsToScreenshot) {
      await processItemThumbnail(
        item.id,
        async () => {
          const { done, value } = await thumbnails!.next(item)
          return done ? undefined : value
        },
        (item.scheduledThumbnailProcessing || generationStrategy) === 'recreate',
      )
    }
  } catch (error) {
    console.error('Error while generating tapestry thumbnail', error)
  } finally {
    // Make sure we finalize the generator, otherwise the Puppeteer (Chrome) browser may remain open.
    await thumbnails?.return()
  }
}
